import HivecrewCore

typealias LocalAccessScopeKind = HivecrewCore.LocalAccessScopeKind
typealias LocalAccessGrantOrigin = HivecrewCore.LocalAccessGrantOrigin
typealias LocalAccessGrantMode = HivecrewCore.LocalAccessGrantMode
typealias LocalAccessGrant = HivecrewCore.LocalAccessGrant
