import HivecrewCore

typealias WritebackOperationType = HivecrewCore.WritebackOperationType
typealias WritebackAutoApplySettings = HivecrewCore.WritebackAutoApplySettings
typealias WritebackFileFingerprint = HivecrewCore.WritebackFileFingerprint
typealias PendingWritebackDeletionTarget = HivecrewCore.PendingWritebackDeletionTarget
typealias PendingWritebackOperation = HivecrewCore.PendingWritebackOperation
