import HivecrewCore

typealias ClusterInfoResponse = HivecrewCore.ClusterInfoResponse
typealias ClusterPeerInfo = HivecrewCore.ClusterPeerInfo
typealias RemoteAccessAPIClient = HivecrewCore.RemoteAccessAPIClient
typealias RemoteAccessError = HivecrewCore.RemoteAccessError
typealias TunnelCreateResponse = HivecrewCore.TunnelCreateResponse
typealias TunnelInfo = HivecrewCore.TunnelInfo
typealias TunnelsGetResponse = HivecrewCore.TunnelsGetResponse
